# Generated by Django 4.0.2 on 2022-02-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpertFinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='address',
            field=models.TextField(default='No address avalible'),
        ),
    ]
