# Generated by Django 4.0.2 on 2022-02-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpertFinder', '0002_alter_cartitems_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
    ]
